### ISSUE TITLE
Be less forgiving about mismatching delimiters

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#107]
Do not import a form when the brackets mismatch, and say that also in the warning. https://github.com/Anaphory/lexedata/blob/b814a35095991fd333adf18f79fd45f57d2d8977/src/lexedata/importer/cellparser.py#L126-L131

**Comment by PaprikaSteiger** [comment]
@Anaphory I decided in the end to move the warnings from the method components_in_brackets to the parse_form method, as the components-method could not influence the control flow of the cellparser to skip the whole form string if a component has mismatching brackets.
Probably it's best if we have a quick look at it at our next coding session.

**Comment by PaprikaSteiger** [comment]
However, not tolerating mismatching delimiters leads to a test that fails:
https://github.com/Anaphory/lexedata/blob/b814a35095991fd333adf18f79fd45f57d2d8977/test/test_cellparser.py#L145-L154

Splitting the form string into components yields:
`['', '<eniãcũpũ>', ' ', '(good-tasting (sweet honey, hard candy, chocolate candy, water))', ')', '{2}', '']`
Though the comment is correctly enclosed with round brackets, the following element consisting only of ')' causes a mismatching delimiter warning and thus let's the test fail.

Is this new behavior desired? (i.e. that parsing a form fails because there's one delimiter too much)

**Comment by nataliacp** [comment]
i think it's fine! can it say you have a mismatching delimiter?
