### ISSUE TITLE
Irrelevant warning on cognates importer

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#132]
When running the cognates importer on Arawak, I get 
```
$ python -im lexedata.importer.cognates Cognates.xlsx 
No 'variants' column found for FormTable in Wordlist-metadata.json. Form variants will be added to #comment.
```
This warning is irrelevant for this context: Forms won't be changed. So we need to be more careful in what circumstances we show what warning.

**Comment by PaprikaSteiger** [comment]
I suspect that this is due to the CognateParser, the importer inherits from the Parser and thus also inherits the warning.

Do you have any suggestions what to do about it? I didn't check the code but I expect that changing the code will make the warning disappear when importing Cognates from excel.
