### ISSUE TITLE
make - and _ uniform?

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#134]
is there a reason that commands (at least some of them) have _ , while arguments (at least some of them) have -? e.g. the segmenter is called segment_using_clts, while one of its arguments is --replace-form. 
I think it is less confusing if one thing is used everywhere. 
Related to that, I am not sure how it is called now, but one script was fromexcel with no separator.

**Comment by Anaphory** [comment]
The `_` in program names vs. `-` in command line switches has reasons: Command line switches begin traditionally with `--`, or `-` for the short versions, but python module names may not contain `-` because that stands for subtraction inside Python.

So the only way to fix that is to implement a big command line wrapper for you to type
```
lexedata enrich segment-using-clts --metadata Wordlist-metadata.json
```
instead of
```
python -m lexedata.enrich.segment_using_clts --metadata Wordlist-metadata.json
```
We can think about doing that, it would also give us the chance to be slightly more helpful with mistyped command names. But I wouldn't give it a high priority for the time being.

Renaming `fromexcel` we should do, though.

**Comment by nataliacp** [comment]
I don't think going through the trouble of a wrapper (which I don't know what it is really) is worth this minor detail. I can see two solutions so we are consistent:
1. we stick to _ in commands and - in options/switches/arguments/whatevers, but we don't have unseparated words
2. we make everything into _ (or this is going to throw off computer people that like their -- to be followed only by - in options?)

**Comment by Anaphory** [comment]
We now have `_` between all words inside commands. I think it would make some sense to have `_` in all the command names and `-` in all the switches and other option names. Which is your option 1, I think? `--some_option` would look odd to me, and the `--` cannot be changed, so I think `lexedata.some_program --some-option` it will have to be, but at least that we can do consistently.

**Comment by nataliacp** [comment]
sounds like a good compromise, hahaha
I could think that there is a generality that says that only the -- are
oddities, and everything else is _, but I totally see your point.
