### ISSUE TITLE
triplicate error messages

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#19]
a mismatching delimiter error seems to cause three separate error messages:
- one without sheet/cell information
- one with sheet/cell info
- one that is about the source (the mismatching delimiter in question was on the source)

Is this expected behavior, or we could simplify?

Here is an example:
In form <che sy'y>(MZ){Pereira1994:68): Encountered mismatched closing delimiter )
Lexical List.J299: In form <che sy'y>(MZ){Pereira1994:68): Element {Pereira1994:68) had mismatching delimiters
In source {Pereira1994:68): Closing bracket '}' is missing, split into source and page/context may be wrong

**Comment by Anaphory** [comment]
The reason it's three messages is because they come from three steps:

1. First, the whole cell is split into different forms. If there are mismatched parentheses, then there might be issues with confusing commas that are supposed to separate different forms and commas that are supposed to be kept because they are in a comment or such like.
 - [ ] So, the first message should make clear that it wants you to check the split of cell value into forms, not the particular form and should 
 - [ ] probably tell you that it expects that everything is fine if there were no commas in the cell. (ERROR when there are commas, WARNING when there are none? Or maybe even INFO?)
 - [ ] The fact that it does not report its cell is also a thing to fix.
2. Then, the separate elements of the form are interpreted. Here, a mismatching delimiter is probably not an issue, but if it is due to a mismatching closing delimiter earlier in the form, it might wreak havoc. These messages should all come after a type-1 message, and where they lead to problems there should always be a type-3 message after them, so
 - [ ] we should not output them in every case, but only if the user explicitly wants them. Probably, we should use the clever `logging` library and take this kind of message down from `WARNING` to `INFO`.
3. Sometimes, we check the internal structure of an element. I think it's useful, because it tells you exactly for what kinds of issues to look for due to the delimiter mismatch.
 - [ ] If it is easy, then this WARNING should also report the cell.

**Comment by nataliacp** [comment]
exactly, I thought that some of these errors necessarily would occur together or not at all, so it may be easier to have them pop up once (or twice if it is necessary). 
the type-3 error (you mean the source one in this case right? that stems from the internal structure check) I think is useful to exist because they could occur independently at a later stage if somebody edits a cell of the database.
