### ISSUE TITLE
long_format and excel comments

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#211]
comments are not read/ignored for long_format, right?

**Comment by PaprikaSteiger** [comment]
This depends a little. When using importer.excel_long_format a Value from an excel column is written to the FormTable **IF**:
- the header of the excel column is identical to the cldf column name (not the cldf name, e.g. `ID` not `id`)
- the matching is case sensitive. E.g. cldf column Name `Comment` but excel column name `comment` does not work
- superfluous columns, i.e. not corresponding to a cldf column in the FormTable, are never written to the dataset. `--ignore-superfluous-excel-columns` just suppresses the Error that is otherwise thrown

Hope this helps

**Comment by nataliacp** [comment]
I meant comments in excel, the ones that are attached to cells. sorry, I should have linked to the manual, this question was not clear at all. https://github.com/Anaphory/lexedata/blob/2ee8240e173645ca243fd29be0771707f78db7a6/Manual/Manual.md?plain=1#L183

**Comment by PaprikaSteiger** [comment]
Oh sorry, yes cell commentas are ignored for long_format
