### ISSUE TITLE
"new" importation format?

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#236]
Should we add the LingPy fromat under the importation to CLDF chapter with a pointer to the add metadata script? Also, what happens if there are partial cognates in the forms.csv (such as in Kellen's dataset)?

**Comment by Anaphory** [comment]
Partial cognates in a separate column are recognized if the column name is “Cognateset_ID” and you guess metadata (run `add_cognate_table` afterwards, it's built exactly for this), or if you have metadata already and run the future not-yet-existing Edictor importer because the partial cogsets are in a Lingpy-style long format.
