### ISSUE TITLE
add_singleton_cognatesets comments and questions

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#260]
- [ ] the description is out of date
- [ ] I am no longer sure what this does. It used to be working only when exporting cognate sets (hence the description), but then we had discussed that it should be able to add them directly to the dataset, no?
- [ ] I thought it would do something to the status column, or it woudl have some kind of automatic name for the cognateset so it is easily findable. What is it? Is it configurable? It is not in the help currently.

**Comment by Anaphory** [comment]
We have the logic implemented in two places:
1. `lexedata.exporter.cognates` is the big and well-tested one.
2. `lexeda.edit.add_singleton_cognate_sets` is the command line script to achieve the same thing without having to export-and-import, but is very rough.

As such,
- [ ] Put the logic that generates the singleton metadata (ID, name, etc.) from https://github.com/Anaphory/lexedata/blob/c8196f23bacbfdc244ae4221dfeb312a65f280cc/src/lexedata/exporter/cognates.py#L287-L324 into a separate function
- [ ] use that function in `lexedata.exporter.cognates`
- [ ] use that function in `lexeda.edit.add_singleton_cognate_sets`
- [ ] fix the command line interface of `lexeda.edit.add_singleton_cognate_sets`, which at the moment is plain bad. Use the CLI of `lexedata.exporter.cognates` as a guideline, so that the arguments and their help is consistent between these two scripts.
