### ISSUE TITLE
matrix importer doesn't skip ? forms

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#377]
I think maybe I should be declaring them in the json somehow, but not sure yet. I will look into it in more detail with the example small maweti dataset.

**Comment by Anaphory** [comment]
You will find nothing there, the matrix importer is not set up to handle ? forms. Never was. Because of its structure, a ? form in the matrix importer expects to have a source, a comment, or some other metadata, and listing ? explicitly is not very helpful.

We only have ? in the interleaved importer, because there is no space for metadata in there, and because that guy needs to keep track of the parallels betwen forms and cognatesets, so there needs to be a way to mark bits for skipping – and mostly for the historical reason that the Bantu dataset had ? and we wrote the interleaved importer specifically for that excel sheet, and didn't kick out the special-case ? afterwards when we renamed it ‘interleaved’.

I think I'd rather remove ? as a special case than add it to the other importers.

**Comment by nataliacp** [comment]
so the nonsense ... forms in the MG dataset would become forms? I think when I modified the maweti json I deleted something about them.

**Comment by nataliacp** [comment]
but I can no longer find it which means that I am remembering something wrong. Great, question solved!

**Comment by Anaphory** [comment]
The ... were in the cognates importer, for special rows that reflected like related concepts or something, right?

I only looked for “?” specifically. We may have had special handling of ... in the cognates importer at some point, but I'll not go digging for it now.

**Comment by nataliacp** [comment]
they were in both spreadsheets. They are trustworthy in the wordlist spreadsheet only. I searched for ... in the small maweti guarani json and I can't find it, so it is not there. Maybe it is in the code somewhere.
