### ISSUE TITLE
Status Column

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexedata#64]
We edit datasets. It would be nice to have a column in many places (all the places?) that comment on the status of those objects, with inter-operable pre-defined values. Sometimes a status needs to be set by an importer, such as adding them to lexedata.exporter.cognates around L. 195 for automatically created singleton cognate sets.

**Comment by Anaphory** [comment]
- [ ] Enrich, glue a status column to every table where that's sensible (i.e. all except #CognateTable)
- [ ] Update scripts that do big automatic things to also update status column when one exists

**Comment by Anaphory** [comment]
If you don't know what to put in the status messages, put a placeholder there and point it out to @nataliacp. I think she's the one who knows best what kind of status messages could be useful.

**Comment by PaprikaSteiger** [comment]
I think: FormTable, CognateTable, CognatesetTable and ParameterTable should have a Status_Column.

These files are candidates for updating the Status_Column. For each file, I proposed a default status update:
- [ ] fromexcel.py (at the moment only status update for Forms or Cognates respectively). Update: "Initial import from excel"
- [ ] importer/cognates
- [ ] exporter/cognates (only output, don't add to dataset)
- [ ] exclesinglewordlist.py
- [ ] align.py
- [ ] cognate_code_data.py
- [ ] guess_concepticon.py
- [ ] guess_concept_for_cognateset.py
- [ ] keep_morpheme_boundaries.py
- [ ] segments_using_clts.py
- [ ] change/rename_concept.py

@Anaphory @nataliacp questions for you:
- [ ] Should the updates be additive? E.g. if you execute exclesinglewordlist.py and then segments_using_clts.py should the latter status update be added or overwrite the existing one?
- [ ] Are the default messages alright?

**Comment by nataliacp** [comment]
fromexcel.py: I think the message could be just "initial import". I think that the status update should apply also to Cognatesets and Parameters, in the case where the whole dataset is imported. When the single wordlist import script is used I think that only forms should be updated (see below).
importer/cognates: this is coming back from the cognate editing xlsx, right? I don't think it should update status, rather it should keep whatever status people may have put for the cognateset table. 
exporter/cognates: I think the status should be "automatic singleton", in the case where a form was not associated to any cognate set. However, I would like to discuss what is done more holistically about new data here, i.e. the name of this new cognate set for easy searching by language. The idea is that the language name should appear somewhere, but I no longer remember what exactly we did with Arawak and if it was the best solution.
excelsinglewordlist.py: this is the case where only forms status should be updated with "new import". I am not sure here if this script should directly make the singleton cognatesets or if the exporter should as we have it now. The reason I am thinking of this is because we want cldf to be valid after a script. So, do we allow forms that are not in cognate sets (within the "policed" concepts) to go without a warning?
align.py: I am not familiar with this script, so I can't comment!
guess_concepticon.py: The update should include automatic: "automatic Concepticon link". I would also like to add here that based on my concept linking with MG, I think for the verification to work with minimal looking up of concepticon, it needs to pull in three things: the concept set ID, the name and the definition. A follow up we could think about would be an option to update name and definition based on the ID for updating the dataset (I don't even know if such updates are common enough, Gereon?)
guess_concept_for_cognateset.py: "automatic Core Concept"
segments_using_clts.py: I am not sure that we want an update here by default. I am imagining a case where you import a bunch of stuff at different times, then you segment so you can export, and then everything becomes "segmented". Assuming the segmenter is solid, I think segmentation is largely hidden from the user and should remain so. I think I would just add a thing in the manual saying if you have weird stuff in your unified forms, then check that the segmentation is correct but that's all. Or maybe this one should be additive and not replace a previous status.
change/rename_concept.py: I am not familiar with this. 

In general I would say overwriting, because it makes searching easier. One exception I can think of is the segmenter you mention Melvin, and maybe the cognateset status that could be used for multiple things at the same time: e.g. review by the team and this core concept assignment (which I think is your last question).

**Comment by Anaphory** [comment]
Keeping segments, and to some extent also core concepts of cognatesets, as properties the user is not expected to engage with and thus something that doesn't need to be reflected in the status column sounds good? Keep in mind that there's always comment columns for more persistent and extensive notes, so it doesn't lose us anything.

**Comment by PaprikaSteiger** [comment]
Thank you, guys. 
I changed the text for the status column and removed the status column as a whole from the three scripts: `segment_using_clts.py, importer/cognates.py, guess_concept_for_cognateset.py`

**Comment by nataliacp** [comment]
ummm, I don't think I agree with you Gereon for core concepts of cognatesets. There is much more fluidity there than segments based on a unified form. maybe we discuss this at our next meeting?

**Comment by Anaphory** [comment]
I thought setting central concepts is much more an editing helper (eg. delete the concepts of messy cognatesets, have them filled in, keep everything else) than a script you call once to update the quality of a cognateset in a stepwise increasing fashion (which is how I conceptualize the status values in general), thus the suggestion.
I don't really mind! If you think guessing central concepts should be tracked, that's fine.

My ideal, in the long run, would anyway be that `--status="blabla"` would override the defaults we set right now, and – depending on what is handier – `--no-status` or `--status=""` would ensure no status is set. That would include the freedom to disagree with the choices we outline right now, so that shoud be fine.
