### ISSUE TITLE
non-uniform behavior of enrich.segment_using_clts

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#76]
This is for the some-hacks-branch so maybe it is already fixed in melvin's branch. I just don't dare switch right now, sorry!
after the importation of all new data in the Arawak dataset, I run the segmenter and I got the following warnings. From the warning it is not clear what is being done. I expected that the segmentation failed, but instead, when I checked there were a number of different outcomes. 
Segments
WARNING:root:Unknown sound '' in form '-p/ po' (segment #3) - the segment / was skipped (I am asking Lev what has happened here, probably alternative forms)
WARNING:root:Unknown sound ''' in form 'kasa'' (segment #5) - this and the following one have a glottal stop at the end? (again I am asking Lev). However, here the segment is not skipped but added as a separate segment to the segments. 
WARNING:root:Unknown sound ''' in form 'úku'u' (segment #4)
WARNING:root:Unknown sound 'áʰ' in form 'ipitáʰnasi' (segment #5)  - this and all the following ones have a superscript h. It has been segmented with the preceding vowel in the segments column. 
WARNING:root:Unknown sound 'áʰ' in form 'uráʰnasi' (segment #3)
WARNING:root:Unknown sound 'eʰ' in form 'hiaseʰni' (segment #5)
WARNING:root:Unknown sound 'áʰ' in form 'dáʰmikasi' (segment #2)
WARNING:root:Unknown sound 'uʰ' in form 'haɻuʰmétata' (segment #4)
WARNING:root:Unknown sound 'iʰ' in form 'nipiʰɻe' (segment #4)
WARNING:root:Unknown sound 'uʰ' in form 'buʰɻaka' (segment #2)
WARNING:root:Unknown sound 'uʰ' in form 'puʰmátakasi' (segment #2)
WARNING:root:Unknown sound 'aʰ' in form 'saʰmétakasi' (segment #2)
WARNING:root:Unknown sound 'eʰ' in form 'háseʰnisi' (segment #4)
WARNING:root:Unknown sound 'iʰ' in form 'uníjapiʰɻe' (segment #7)
WARNING:root:Unknown sound 'éʰ' in form 'mabéʰniɻi' (segment #4)
WARNING:root:Unknown sound 'aʰ' in form 'jaʰnébúɻu' (segment #2)
WARNING:root:Unknown sound 'áʰ' in form 'pabuáʰɻeɻi' (segment #5)
WARNING:root:Unknown sound 'iʰ' in form 'kabiʰɻimi' (segment #4)
WARNING:root:Unknown sound 'aʰ' in form 'daʰmitukáɻusi' (segment #2)
WARNING:root:Unknown sound 'aʰ' in form 'daʰmítukasi' (segment #2)
WARNING:root:Unknown sound 'iʰ' in form 'siʰmákasi' (segment #2)
WARNING:root:Unknown sound 'aʰ' in form 'kitaʰwasi' (segment #4)
WARNING:root:Unknown sound 'aʰ' in form 'nitaʰni' (segment #4)
WARNING:root:Unknown sound 'aʰ' in form 'jaʰmáɻakasi' (segment #2)
WARNING:root:Unknown sound 'aʰ' in form 'jaʰne' (segment #2)
WARNING:root:Unknown sound 'aʰ' in form 'jaʰne' (segment #2)

**Comment by Anaphory** [comment]
So far so okay, the documentation should indeed be better and tell you that the intended strategy of the segmenter is to greedily create segments, and if it fails to add the glyph to the segment string unchanged. That should explain the `'` being put into the forms as-is.

`/` is a very special character in CLTS, and I would have expected the segmenter to just die on us when given a form that contains it.
 - [ ] Maybe we should indeed change it to explicitly fail on `/` instead of writing out empty segment nonsense.

`ʰ` is notoriously difficult for CLTS to deal with, because the greedy segmenter cannot, at the time of segmenting, distinguish between its use as pre- and post-aspiration marker, and therefore assumes it's always post. I think it's the only IPA modifier that can come before a letter and has a different meaning then? I don't know how we could sensibly work around it. Should we try? (I'm not sure whether to consider this a bug in CLTS or not, the CLTS devs definitely don't.)

**Comment by PaprikaSteiger** [comment]
I enhanced the warning by the sentence `"Sound was added unchanged to segments."` Is that enough?

So, should it fail on `/` or not?

**Comment by nataliacp** [comment]
I think the additional sentence is good. and I would vote for failing on /
and saying go fix it!
