### ISSUE TITLE
treatment of superscript segments

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#77]
The original Arawak data have a number of superscript segments in the unified form that have become regular segments in the dataset. Why is this? How could we recover them? 
Also, is the segmentation of somehting like tʰ supposed to be t h ?
an example is the form for bow in Tariana. (form id 29411)
the newly imported data however have no problem (e.g. Bare new data have superscript h, while the old data don't). However, Warekena Velha (Guainia) has vowels followed by superscript h that throw a warning. They are segmented as a unit though in the segments.

**Comment by Anaphory** [comment]
Hm. That should definitely not happen:

    >>> from segments import Tokenizer
    >>> Tokenizer()("tʰest", ipa=True)
    'tʰ e s t'

I suspect it's not an actual tʰ, but a t<sup>h</sup>: The h is not actually [U+02B0](https://en.wikipedia.org/wiki/Aspirated_consonant), but an h with superscript formatting. We have no way to access character level formatting, so not even a theoretical way to recover it.

**Comment by nataliacp** [comment]
no superscript survived the first import, and all of them seem fine in this second one. Both were done from google sheets so I think something else is going on. Could it be that the importer was not as smart in the beginning.

**Comment by Anaphory** [comment]
I have an idea. I hope I'm wrong :disappointed: 
When we were running the unicode normalization…
The one with NFKC…
Clearly, ʰ and h are ‘compatible’ in unicode terms. So I bet the error is in that step, and never got noticed so far and never got fixed, and now there's a pile of other things on top of it.
If we are lucky, `th` doesn't occur otherwise, thet it's search&replace. Otherwise it's going to be a painful merge with an earlier version.
